### PR TITLE
Add "default" construction type to use fixed time constant (tau) from SIA 2024

### LINKED ISSUE #651: Hizard - Create a "default" construction type that takes tau from SIA 2024 (non-variable)
## Problem

Currently the construction type selection uses room specific heat capacity values from SIA 380 construction templates. These are then used to variably calculate tau in the sia380 component.

Previously, we only used fixed tau values from SIA 2024.

## Proposal

- reintroduce fixed tau for calculations from SIA 2024
- enabled (from user side) when selecting "default" from construciton types drop down
- add tooltip for clarity

Related to #647

### PR DESCRIPTION
**Pull request by maxenceryan**
## Issues

Closes #651 

## Description

- add a "default" construction type option in the hizard
  - when selected, in the background a boolean called UseFixedTimeConstant is assigned to true
  - this boolean is passed similarly to RunAdaptiveComfort through the SIA distributor and into SIA 380 component
  - within sia380, the tau value from SIA 2024 rather than calculating it based on capacities (as is the case when selecting other construction types

image
image
image

results with default (fixed tau) selected:
image
results with superlightweight (more heating and cooling demand, as expected):
image

## Checklist

- [x] Remove debugging artifacts (if needed)
- [x] Rebuild the Setup_Hive.exe
- [x] Update Hive Wiki (if needed)
- [x] Update most important Grasshopper template(s); as of now [/GrasshopperExamples/LectureExercises/EaCS3_E04_Hive_Template.gh](https://github.com/architecture-building-systems/hive/blob/master/GrasshopperExamples/LectureExercises/EaCS3_E04_Hive_Template.gh)

### CODE REVIEW

**Comment by christophwaibel** [comment]
@maxenceryan 
unfortunately, there is still some significant difference in heating/cooling loads between v1.10.2 and this current PR. I do think, we should understand where this comes from, because there shouldn't be a difference.

I tried with the exercise file from the Hive online course, M04: https://moodle-app2.let.ethz.ch/mod/folder/view.php?id=590820
- natural ventilation deactivated in new build
- adaptive comfort connected to 80% range in v1.10.2 (and in new build)
- variable tau set to "default" in new build

v1.10.2
v1 10 2_80percComf

new PR
PR

**Review by christophwaibel — CHANGES_REQUESTED** [review]
see my comment https://github.com/architecture-building-systems/hive/pull/653#issuecomment-927189067

**Comment by maxenceryan** [comment]
OK so I dug through all the changes one by one in sia380 but, given the same inputs, I could not find significant differences (apart from floating point errors). I tried this out outside of grasshopper with the same argument values for both the PR and v10.2.

Then in grasshopper, i checked the inputs to both GH files. One of them actually had adaptive comfort bounds set to 90, so I changed it to 80 as you described. I then compared inputs in both files and although there are many differences (additional SIA room properties, rearranged room_schedules JSON, surface_types by component instead of just transp/opaque), **the only major difference is the zone floor area**.

We at some point implemented a net zone area based on SIA recommendations of multiplying the gross floor area by 0.9 (see commit https://github.com/architecture-building-systems/hive/commit/19e19d7173fc5cc5ea00e7431acbce1b2e6f22ac). You'll notice the difference in floor_area of the two GH files. The repercussions are that Q_i, Q_Elec and Q_V go down as they are all tied to per m2 values from SIA. This then affects the eta_g values which in turn alter all other outputs of the sia380 module.

I've attached the inputs (except for the hourly temperatures and solar profiles, as those dont change) and outputs as JSONs so you can compare them, but you will find the Q_i from the different versions almost exactly get multiplied by 0.9.

So from what I can tell this is what is happening.
[fixedtauPR_comparison_jsons.zip](https://github.com/architecture-building-systems/hive/files/7247528/fixedtauPR_comparison_jsons.zip)

**Comment by christophwaibel** [comment]
ahhhh!!! totally forgot about that! thanks a lot for solving this mystery. I can properly describe it then in the next Release. 

OK from my side to merge

**Comment by christophwaibel** [comment]
hold up... but why are *cooling* loads going up though, in comparison to v.1.10.2?

**Comment by christophwaibel** [comment]
ok according to the files you attached, loads do look ok in comparison between versions.
I must have overlooked something then in my fast grasshopper tests... maybe because at some point, we also fixed a bug where all construction U-values where identical?

**Comment by christophwaibel** [comment]
[GHfiles.zip](https://github.com/architecture-building-systems/hive/files/7248050/GHfiles.zip)

OK I made sure to have all parameters identical and I can now also reproduce similar results between both versions, with the difference being plausible explained by the reduced floor area in the new PR.

NOW I'm ok with merging ;-)

**Review by christophwaibel — APPROVED** [review]

**Pull request merged**
