### PR TITLE
529 GH_Visualizer Axis Limits Input

### LINKED ISSUE #529: UI/UX design of inputting axis limits of GhVisualizer
Currently, you have to click on the axis to open a form dialogue. It's functional, but not very sexy:

Is it possible to get some sort of hover-over effects? @daren-thomas 

mouse no hover over "RunSA"

mouse hover over "RunSA", button becomes bright

Also, the dialogue can be designed better. This sounds like a job for Designer-Amr! @amraladdin  :)

### PR DESCRIPTION
**Pull request by philipschulz**
# Axis Limits Input

## Issues

Closes #529 

## Description

- Draws a box around the clickable Area when hovering over the Y-Axis
- Double clicking in that area brings up the Axis Limit Input Window

## Checklist

- [ ] Remove debugging artifacts (if needed)
- [x] Rebuild the Setup_Hive.exe
- [ ] Update Hive Wiki (if needed)
- [ ] Update InformationalVersion attribute in Hive.IO/Properties/AssemblyInfo.cs (if it's a new release) 
- [ ] Update most important Grasshopper template(s); as of now [/GrasshopperExamples/LectureExercises/EaCS3_E04_Hive_Template.gh](https://github.com/architecture-building-systems/hive/blob/master/GrasshopperExamples/LectureExercises/EaCS3_E04_Hive_Template.gh)

### CODE REVIEW

**Comment by christophwaibel** [comment]
Hi Philip, awesome! Works pretty well on my computer, no performance issues. But then, I have a fast CPU...
I suggest some improvements:

- when the unit is set to `/m2`, the axis form should also change it's unit / range correspondingly
image
- The box should not appear in the gains-vs-losses and not in the Amr plots: 
image

**Comment by ChrisZenhub** [comment]
@christophwaibel try performance also with Macbook

**Comment by christophwaibel** [comment]
> @christophwaibel try performance also with Macbook

performance of visualizer is fine on Parallels, Macbook with 2.3GHz i7

**Comment by philipschulz** [comment]
@christophwaibel Looking into it, the Axis Limit Input currently completely lacks the ability to edit the axis when in kwh/m2 viewmode, is that something that should change? Because that is why the numbers/units don't change when switching to normalized per m2 view

**Comment by philipschulz** [comment]
Oh and I'll have to change that the axis input also appears and the box is drawn when on the "Solar Gains per Windows" view
image

**Comment by christophwaibel** [comment]
> And I'll have to change that the axis input also appears and the box is drawn when on the "Solar Gains per Windows" view image

Hey @philipschulz can you make a new issue for those? Let's merge this PR first

**Comment by christophwaibel** [comment]
image

@philipschulz it works on the energy demand plot, but now it unfortunately is also deactivated on the Solar Gains plot

**Comment by philipschulz** [comment]
@philipschulz Yes but didn't you say I should open a new issue for that, so that this PR could be closed?

**Comment by christophwaibel** [comment]
> @christophwaibel Yes but didn't you say I should open a new issue for that, so that this PR could be closed?

oh I see, misunderstanding. I though you were referring to the axis input form only. Please still add the double click for the Solar Gains plot to this PR. Thanks!

**Comment by philipschulz** [comment]
@christophwaibel The axis box now works correctly on all necessary plots

**Comment by christophwaibel** [comment]
works, thanks @philipschulz !

**Pull request merged**
