### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by maxenceryan**
might be useful for user testing

### CODE REVIEW

**Review by christophwaibel — CHANGES_REQUESTED** [review]
that's cool! Just me being uncultured: So how do users access it? I see, it is in `.github/ISSUE_TEMPLATE`, but how would someone find it? Can you add a description to the wiki `https://github.com/architecture-building-systems/hive/wiki/Troubleshooting`?. After that, you can merge :-)

**Comment by maxenceryan** [comment]
I think it shows up when you create a new issue. But I will merge this first asit needs to be in maste rto test it out.

**Comment by maxenceryan** [comment]
ok now I see this when i click new issue 
image

**Comment by maxenceryan** [comment]
slightly different in zenhub 
image

**Comment by maxenceryan** [comment]
updated the wiki

**Pull request merged**
