### PR TITLE
461 remember changed input parameters in the WPF forms (Building and EnergySystems)

### PR DESCRIPTION
**Pull request by daren-thomas**
This PR implements #461 by overriding Read() and Write() in GhBuilding and GhEnergySystems.

To test: Edit the building / energy systems. Save. Close document. Open document. Check if it loaded properly.

Maybe pay special attention to the meshes / surfaces for PV / ST.

### CODE REVIEW

**Comment by christophwaibel** [comment]
image

upon opening, it gives this message. Is this intended?

[EaCS3_E02_Hive_BuildingDemand.zip](https://github.com/architecture-building-systems/hive/files/5422483/EaCS3_E02_Hive_BuildingDemand.zip)

**Comment by christophwaibel** [comment]
image

they disappear once you've changed something, saved the `.gh` file, closed rhino, and reopened the file

**Comment by christophwaibel** [comment]
image

these numbers in PV and in Solar Thermal are not saved when closing Rhino.

All other parameters in both the Building and EnergySystems form seem to be saved properly

**Review by christophwaibel — CHANGES_REQUESTED** [review]
amazing! works for most parts. please see my comments directly in #471 for bugs

**Comment by ChrisZenhub** [comment]
@daren-thomas let's make separate issues for these 2 bugs:
- "failed to read state..." message should disappear once the form was opened and closed
- PV and ST parameters are not saved

**Pull request merged**
