### PR TITLE
added area computation, show specific cost / emissions for photovoltaic & solar thermal

### PR DESCRIPTION
**Pull request by daren-thomas**
This PR addresses #385 (energy systems form some data not shown)

open questions: 

- what is the unit of the json file for specific cost / specific emissions? 
  - [CHF/kWp] or
  - [CHF/m2]

### CODE REVIEW

**Comment by daren-thomas** [comment]
@christophwaibel I don't believe the Capacity for SurfaceTech types really follows this equation: `Area * Efficiency` - we're specifying efficiency as (%). ideas?

**Comment by christophwaibel** [comment]
if we assume 1kW/m2 solar radiation, we can translate to capacity (in kW_peak) = totalArea (in m^2) * refEfficiency (fraction from 0 to 1)
so yes, the equation should be ok @daren-thomas

**Comment by christophwaibel** [comment]
by the way, that translation is happening in the constructor of `Photovoltaic` and `SolarThermal` and then you could access `SurfaceBased.Capacity` (in kW_peak for surface based tech).

Maybe it would be more consistent to access such properties from the conversion tech object, instead of hardcoding it separately into the ViewModel?

**Comment by daren-thomas** [comment]
@christophwaibel maybe. but - we don't always have such an object (for non-parametric items - but we could also change that. later).

**Comment by daren-thomas** [comment]
also fixes #391 (energy systems form has wrong parameter names)

**Pull request merged**
