### PR TITLE
Make AmrPlot online + other improvements to visualiser

### LINKED ISSUE #337: feed real data into ResultsPlotter for AmrPlot
...and maybe rename it to `ResultsAdaptor`

### LINKED ISSUE #551: design updates to the AmrPlot
some revisions to the design of the AmrPlot in the GhVisualizer, as discussed in our AmrPlot workshop. slides 12-15 here:

https://docs.google.com/presentation/d/1FJ1ZZXHWV4lAlZivqtyNx2I8tnIDKTHHKmVih2kN1ME/edit#slide=id.gb146780c39_0_376

- rename "embodied" and "operation" to "initial" and "recurring" (slide 12)
- change time resolution button to have 4 resolutions: "Total" (assuming a fixed lifetime), "Yearly", "Monthly", "Hourly"
- change plot units depending on the time resolution. For "total", units are not /year, but the total values, where we assume a lifetime of the building
- add a "Total Lifetime = ...?" text somewhere (beneath the time resolution button`? only pops up when "Total" is selected as time resolution)
- delete y-axis for non-time series data (e.g. embodied carbon emissions), even if "month" or "hourly" is selected
- non time-series data is shown as one rectangle, proportional to its quantity. Basically what we already have, but not drawing , e.g. for "Monthly", 12 separate bars

### LINKED ISSUE #620: Data provided in kWh/a/m2 (energy demand chart) would be helpful
Hi

These comments are regarding the **energy demand graph** 

**1.** It is maybe obvious, that the energy demand in the upper right corner is in **kWh/a** (annual). The small "a" would help me.
Bildschirmfoto_Hive_kWh

**2.** It would be nice to have an option to change the visualisation of the chart to **kWh/m2**
If somebody changes the geometry of the building, the ground floor area would also change. You can properly compare the energy performance of your alternatives only in kWh/m2.

### LINKED ISSUE #632: check correctness of KPI values in Visualizer

### LINKED ISSUE #650: visualizer KPI buttons on click should change unit to per m2
**Describe the bug**
The KPI buttons on the top right of the visualizer were once able to change their units (e.g. from kWh to kWh/m2) by clicking on them. Not sure, why this doesn't work anymore.

**Screenshots**
image

**Software**
 - Hive Version 1.12

**Additional context**
Related issue #620 . Changing the unit via the KPI button could also automatically change the unit of the graphs, as @lillaa suggests

### PR DESCRIPTION
**Pull request by maxenceryan**
## Issues

Closes #632 

Closes #337 

Closes #650 

Closes #551

Closes #620

## Description

- reinsert the AmrPlot with real data
- enhance AmrPlot embodied cost calculations with levelised calculations
  - now considers actual interest rate (default to 5%), building lifetime (default to 80 years)
  - lifetime of systems and building components also assigned default values
- some restructuring of Results class to consistently store results along different dimensions of AmrPlot (time resolution, embodied vs operation, systems vs buildings)
- enable normalized vs non normalized plots for Energy Balance, AmrPlot, Performance
- consolidated some notes on sources into a single markdown

## Checklist

- [ ] Remove debugging artifacts (if needed)
- [ ] Rebuild the Setup_Hive.exe
- [ ] Update Hive Wiki (if needed)
- [ ] Update most important Grasshopper template(s); as of now [/GrasshopperExamples/LectureExercises/EaCS3_E04_Hive_Template.gh](https://github.com/architecture-building-systems/hive/blob/master/GrasshopperExamples/LectureExercises/EaCS3_E04_Hive_Template.gh)

### CODE REVIEW

**Comment by maxenceryan** [comment]
@christophwaibel still WIP, but i recommend you try these changes out quickly from a user perspective without going through the code, so we can see what is working / what is misisng. It is worth changing some cost values in the energy systems winforms, because the default values are pretty small and wont show up in contrast to the building embodied costs. (such as for chiller, something like 12CHF/kw). 

You'll have to recreate the setup exe first as well 😄 

A few things to clarify:

- embodied "energy" in the AmrPlot: what does this mean and how would this be calculated? For now it is left blank
- are the listed AmrPlot improvements as part of #551 still valid? perhpas we should just discuss this
- other tings i forgot meow... 🤔

**Comment by christophwaibel** [comment]
> @christophwaibel still WIP, but i recommend you try these changes out quickly from a user perspective without going through the code, so we can see what is working / what is misisng. It is worth changing some cost values in the energy systems winforms, because the default values are pretty small and wont show up in contrast to the building embodied costs. (such as for chiller, something like 12CHF/kw).
> 
> You'll have to recreate the setup exe first as well 😄
> 
> A few things to clarify:
> 
> * embodied "energy" in the AmrPlot: what does this mean and how would this be calculated? For now it is left blank
> * are the listed AmrPlot improvements as part of [design updates to the AmrPlot #551](https://github.com/architecture-building-systems/hive/issues/551) still valid? perhpas we should just discuss this
> * other tings i forgot meow... 🤔

Niiice! @amraladdin will be happy to see this ;-) 
We already discussed some of the points in our last meeting. Summarizing:

- embodied energy, see Google Doc, slide 6 (https://docs.google.com/presentation/d/1FJ1ZZXHWV4lAlZivqtyNx2I8tnIDKTHHKmVih2kN1ME/edit): subset of embodied emissions (e.g. from KBOB); energy that is needed to produce materials etc... We reckon, it is difficult to acquire such data. For some parts, the Amr plot (quadrant-idea) does not fully work. Probably leave empty for now until we have a re-design of the plot
- yes, they are still valid. some points would need to be revised though. 


Comments from a user perspective, ranked according to importance (imo):
- Visualizer crashes if no proper data is plugged in. E.g., when dragging the visualzier onto the GH canvas, that would result in an error. Needs some routine to draw plot with zero data, similar to how the other plots implement it in the Visualizer
- Plot could need a Y-axis. Also, what are those "x" labels on the X-axis? image
- hover-over quadrants could need tooltips. E.g., when mouse hovers over the quadrant for "emobied-emissions-building", would be nice to have a little tooltip that briefly explains this plot
- text label cut off, if visualizer size is too small. could need an indicator "(...)" that there's still text coming, or similar image
- double-click on visualizer opens form to change Y-axis range. A bit annoying 
image

**Comment by maxenceryan** [comment]
per discussion:

**Previous points**
- Visualiser fatal error is now resolved, with some improvements to other plots as well to avoid crashing of grasshopper. Also robust with false inputs
- x marks in monthly plots and values of each bar added as a small caption
- tooltips not implemented as easy to do with WinForms, but AmrPlot is a custom component that does not use WinForms. Potential text has been added under AmrPlotConstants but for now does not do anything. Could be added in a help window as part of #656
- overflow text for assumptions now has ellipsis (...)
- redesigning axis changes has been created in separate issue #656 

**New review comments (TODO)**
- [ ] Energy - Operational - Systems seems odd at monthly basis. Should be following the demand curves but is flat. Check calcs
- [ ] Remove decimals from KPI values, as these are rough calculations
- [ ] Remove the sum/average numbers for energy, esp percentage, as it is double counting.

**Comment by maxenceryan** [comment]
ready for reviooooo

**Review by christophwaibel — APPROVED** [review]
damnn, son, what a massive PR! 
Amr plot works like a charm!
Some data might not yet make fully sense (energy -> systems vs buildings seem strange), but that is something for the Hive.Core (i.e., the Spagette)

**Pull request merged**
